In [24]:
import pandas as pd
import glob

Archivos = glob.glob('Files/*')




DataFrameLectura = pd.read_excel("Files/Precio_Bolsa_Nacional_($kwh)_1995.xlsx",skipsrows =1, usecols = list(range(26)))
DataFrameLecturaCopia = DataFrameLectura.copy()
IndiceDelaColumnaFecha= DataFrameLecturaCopia[DataFrameLecturaCopia.columns[0]] == 'Fecha'

In [34]:
def LeerPrecios(filename):
    for indice in range(10):
        df = pd.read_excel(filename,skipsrows = indice, usecols = list(range(26)))
        if df.iloc[0,0] == 'Fecha':
            df = pd.read_excel(fiename,skipsrows = indice+1, usecols = list(range(26)))
            break
    return df

In [37]:
ArregloProcesado = LeerPrecios("Files/Precio_Bolsa_Nacional_($kwh)_1995.xlsx")
ArregloProcesado

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Precio Bolsa Nacional ($/kWh) 1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fecha,0.000,1.000,2.000,3.000,4.000,5.000,6.000,7.000,8.000,...,14.000,15.000,16.000,17.000,18.000,19.000,20.000,21.000,22.000,23.000
3,1995-07-20,NaN,1.073,1.073,1.073,1.073,1.073,1.073,1.073,1.074,...,1.073,1.073,1.073,1.073,1.074,1.897,1.897,1.897,1.073,1.073
4,1995-07-21,1.073,1.000,1.000,1.000,1.000,1.000,5.000,6.000,6.000,...,5.000,1.000,1.000,5.000,12.000,16.670,11.929,5.000,1.000,1.000
5,1995-07-22,1.073,1.073,1.000,1.000,1.000,1.073,1.303,1.303,1.303,...,1.073,1.000,1.000,1.000,1.303,2.500,2.500,1.303,1.073,1.073
6,1995-07-23,1.073,1.000,1.000,1.000,1.000,1.000,0.100,1.000,1.000,...,1.000,0.100,0.100,1.000,1.238,1.238,1.238,1.238,1.073,1.000
7,1995-07-24,1.000,1.000,0.990,1.000,1.000,1.073,3.000,3.000,3.000,...,1.073,1.073,3.000,2.000,18.630,22.500,9.256,3.000,1.073,1.000
8,1995-07-25,0.990,0.990,0.989,0.990,0.990,1.073,1.263,1.263,1.263,...,1.073,1.073,1.073,1.073,1.263,1.500,1.263,1.263,1.073,0.990
9,1995-07-26,0.500,0.500,0.500,0.500,0.500,0.990,1.073,1.073,1.073,...,0.500,0.500,0.990,0.990,1.073,8.000,1.073,0.990,0.500,0.000
10,1995-07-27,0.500,0.500,0.500,0.500,0.500,0.500,0.500,0.500,0.500,...,0.500,0.500,0.500,0.500,1.073,1.500,0.990,0.500,0.500,0.500
11,1995-07-28,0.000,0.000,0.000,0.000,0.000,0.463,0.463,1.000,0.463,...,0.463,0.463,0.463,0.463,1.073,1.073,1.073,1.000,0.000,0.000
12,1995-07-29,1.000,1.000,0.000,0.000,1.000,0.000,1.070,1.070,1.070,...,1.070,1.070,1.070,1.070,1.070,1.070,1.072,1.070,1.070,1.070
13,1995-07-30,1.072,1.000,0.000,0.000,0.000,0.000,0.100,1.000,1.072,...,1.000,0.000,0.000,0.100,1.072,1.073,1.073,1.072,1.072,0.000
14,1995-07-31,0.000,0.000,0.000,0.000,0.000,1.000,1.073,0.000,0.000,...,0.000,0.000,0.000,0.000,1.073,8.845,1.073,1.073,1.000,0.000
15,1995-08-01,0.000,0.000,0.000,0.000,0.000,1.070,1.073,0.000,1.070,...,0.000,0.000,0.000,0.000,1.070,1.073,0.000,0.000,0.000,0.000
16,1995-08-02,1.073,1.073,1.073,1.073,1.073,1.073,1.100,1.073,1.073,...,1.073,1.073,1.100,1.073,1.073,1.073,1.073,1.100,1.073,1.073
17,1995-08-03,1.073,1.073,1.073,1.073,1.073,1.100,2.000,2.000,2.000,...,1.073,1.073,1.500,1.073,2.000,2.000,2.000,2.000,1.100,1.073
18,1995-08-04,1.073,1.073,1.073,1.073,1.073,2.000,2.000,2.000,2.000,...,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,1.500
19,1995-08-05,2.000,2.000,2.000,1.073,2.000,2.500,2.500,2.558,2.558,...,2.500,2.500,2.500,2.500,2.558,2.558,2.558,2.558,2.500,2.500
20,1995-08-06,3.000,1.073,1.073,1.073,1.073,3.000,3.000,3.000,3.200,...,3.000,1.070,1.070,1.000,3.000,3.200,3.200,3.200,3.000,1.070
21,1995-08-07,3.000,3.000,3.000,1.073,3.000,3.000,3.500,3.500,3.700,...,3.500,3.500,3.500,3.500,5.000,8.000,5.000,5.000,3.500,3.000
22,1995-08-08,3.000,3.000,3.000,3.000,5.800,7.000,7.000,9.000,8.000,...,7.000,7.000,7.000,7.000,8.000,9.000,8.000,8.000,7.000,5.800
23,1995-08-09,10.000,10.000,10.000,10.000,10.000,13.788,17.000,15.000,15.000,...,13.788,13.788,13.788,13.788,16.001,16.001,16.001,15.000,13.788,12.000
24,1995-08-10,18.000,18.000,18.000,18.000,18.000,18.000,21.000,21.000,21.000,...,21.000,21.000,21.000,21.000,21.000,22.000,21.000,21.000,18.000,18.000
25,1995-08-11,12.000,6.000,6.000,6.000,22.600,25.000,25.000,25.000,25.000,...,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,6.000
26,1995-08-12,30.000,15.000,1.074,15.000,17.500,30.000,30.000,31.000,40.000,...,31.000,31.000,31.000,31.000,40.000,40.000,40.000,39.492,31.000,30.000
27,1995-08-13,35.000,18.000,17.000,18.000,18.000,24.600,32.000,39.492,40.000,...,40.000,39.492,39.492,39.492,40.000,40.000,40.000,40.000,40.000,23.300
28,1995-08-14,17.000,1.074,12.000,12.000,17.500,39.492,40.000,40.000,40.000,...,40.000,40.000,40.000,40.000,40.000,40.000,40.000,40.000,40.000,17.500
29,1995-08-15,1.074,1.074,1.074,1.074,1.074,17.500,20.000,20.000,20.000,...,20.000,20.000,20.000,20.000,20.000,23.300,20.000,20.000,1.074,1.074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,1995-12-02,120.000,120.000,120.000,120.000,120.000,120.000,73.000,117.112,117.112,...,130.000,90.000,130.000,130.001,117.112,117.112,117.112,117.112,130.001,130.000
139,1995-12-03,130.001,130.001,130.001,130.001,130.001,130.001,117.112,130.000,124.627,...,73.000,73.000,73.000,130.001,124.627,124.627,124.627,130.001,130.001,130.001
140,1995-12-04,160.001,160.001,135.000,130.002,160.000,135.001,132.001,132.001,132.001,...,132.001,132.001,130.003,130.001,130.001,124.627,124.627,130.003,135.001,135.001
141,1995-12-05,78.620,78.620,24.500,40.882,70.734,137.413,137.413,137.413,137.413,...,137.413,137.413,137.413,137.413,137.413,137.413,137.413,137.413,137.413,137.413
142,1995-12-06,22.300,22.300,22.200,22.200,22.400,22.400,147.070,147.070,147.070,...,73.000,79.627,147.070,147.070,147.070,147.070,147.070,147.070,73.000,73.000
143,1995-12-07,31.716,31.716,31.716,31.716,31.716,31.716,100.000,156.248,156.248,...,79.627,79.627,156.248,156.248,156.248,156.248,156.248,156.248,73.000,73.000
144,1995-12-08,20.000,15.468,15.468,14.000,15.468,20.000,22.400,22.400,32.913,...,25.000,25.000,25.000,25.000,170.263,170.263,170.263,73.000,73.000,73.000
145,1995-12-09,79.627,22.400,22.400,22.400,22.400,32.913,170.600,170.600,170.600,...,170.600,170.600,170.600,170.600,170.600,170.600,170.600,170.600,170.600,170.600
146,1995-12-10,172.660,88.524,40.000,79.627,79.627,36.900,30.000,172.660,172.660,...,172.660,172.660,172.660,172.660,172.660,172.660,172.660,22.400,172.660,28.900
147,1995-12-11,30.000,20.000,20.000,20.000,36.900,22.300,36.900,179.730,179.730,...,100.000,179.730,179.730,179.730,179.730,179.730,179.730,179.730,100.000,73.000
148,1995-12-12,40.000,40.000,40.000,40.000,40.000,40.000,73.000,179.001,179.001,...,179.001,179.001,179.001,179.001,179.001,179.001,179.001,179.001,100.000,73.000
149,1995-12-13,60.000,55.000,55.000,50.000,55.000,60.000,120.000,120.000,120.000,...,120.000,120.000,120.000,120.000,179.000,179.000,120.000,120.000,60.000,36.900
150,1995-12-14,20.000,20.000,20.000,20.000,20.000,20.000,40.000,55.000,60.000,...,79.627,60.000,60.000,60.000,120.000,120.000,69.810,80.000,60.000,60.000
151,1995-12-15,20.000,16.640,15.000,15.000,20.000,20.000,60.000,60.000,60.000,...,60.000,60.000,60.000,60.000,100.000,100.000,60.000,55.000,60.000,50.000
152,1995-12-16,15.000,15.000,15.000,15.000,15.000,15.000,60.000,60.000,60.000,...,60.000,60.000,12.600,15.000,80.000,80.000,80.000,60.000,80.000,60.000
153,1995-12-17,9.890,1.500,1.500,1.500,1.500,1.500,10.000,13.000,13.700,...,55.000,32.913,20.000,55.000,60.000,60.000,55.000,55.000,55.000,20.000
154,1995-12-18,20.000,15.000,15.000,20.000,30.000,55.000,55.000,55.000,55.000,...,30.000,55.000,55.000,55.000,65.000,65.000,60.000,60.000,55.000,55.000
155,1995-12-19,40.000,40.000,40.000,40.000,40.000,60.000,65.000,65.000,65.000,...,71.000,71.000,71.000,75.001,75.001,75.001,75.001,75.001,70.000,60.000
156,1995-12-20,40.000,40.000,40.000,40.000,40.000,60.000,60.000,60.000,60.000,...,60.000,60.000,60.000,60.000,75.001,71.000,75.001,80.000,71.000,60.000
157,1995-12-21,40.000,30.000,30.000,30.000,40.000,60.000,70.000,70.000,70.000,...,70.000,70.000,70.000,70.000,80.000,75.000,75.000,70.000,70.000,60.000
158,1995-12-22,15.000,15.000,15.000,15.000,15.000,18.465,40.000,60.000,60.000,...,40.000,60.000,60.000,60.000,75.000,75.000,60.000,60.000,60.000,60.000
159,1995-12-23,13.700,1.074,1.074,1.074,12.650,15.000,20.000,20.000,20.000,...,20.000,20.000,20.000,20.000,60.000,60.395,60.000,42.131,20.000,20.000
160,1995-12-24,40.000,35.000,30.000,21.000,21.000,32.700,9.700,15.000,18.465,...,5.000,5.000,1.074,9.700,60.000,60.000,60.000,19.900,30.000,30.000
161,1995-12-25,18.465,15.000,1.074,1.074,1.074,1.074,1.074,1.074,1.074,...,1.074,1.074,1.074,1.074,60.000,60.000,60.000,15.000,10.000,10.000
162,1995-12-26,19.900,15.000,15.000,15.000,16.640,25.000,15.000,15.000,25.000,...,15.000,15.000,15.000,20.000,40.000,40.000,40.000,25.000,15.000,15.000
163,1995-12-27,15.000,15.000,15.000,15.000,15.000,15.000,15.000,15.000,15.000,...,15.000,15.000,15.000,15.243,41.000,41.000,40.000,40.000,15.000,10.000
164,1995-12-28,14.900,14.900,14.900,14.900,14.900,15.000,25.000,25.000,25.000,...,25.000,25.000,25.000,30.000,41.000,41.000,41.000,15.000,15.000,14.900
165,1995-12-29,11.990,11.990,11.990,11.990,15.000,15.243,13.600,30.000,30.000,...,30.000,20.000,14.300,30.000,41.000,41.000,41.000,40.000,30.000,13.700
166,1995-12-30,13.500,12.000,12.000,12.000,9.700,13.500,14.300,18.000,30.000,...,14.990,14.990,8.052,12.000,40.000,41.000,40.000,40.000,14.990,13.000
167,1995-12-31,15.000,14.990,14.990,14.990,14.990,14.990,14.990,12.000,13.000,...,11.990,1.074,1.074,1.074,14.350,20.000,13.700,14.990,30.000,18.000

In [65]:
def leer_precios(filename):
    for k in range(10):
        df = pd.read_excel(filename,
                           skiprows = k,
                           usecols = list(range(25)))
        if df.iloc[0,0] == 'Fecha':
            df = pd.read_excel(filename,
                               skiprows = k+1,
                               usecols = list(range(25)))
            break
        
    return(df)
    
    
    
  
filenames = !ls Files/*.xls*
dfs = []
for filename in filenames:
    dfs.append(leer_precios(filename))
dfs = pd.concat(dfs)
dfs.size
dfs = pd.melt(dfs,id_vars='Fecha')

In [66]:
dfs

             Fecha variable       value
0       1995-07-20        0         NaN
1       1995-07-21        0    1.073000
2       1995-07-22        0    1.073000
3       1995-07-23        0    1.073000
4       1995-07-24        0    1.000000
5       1995-07-25        0    0.990000
6       1995-07-26        0    0.500000
7       1995-07-27        0    0.500000
8       1995-07-28        0    0.000000
9       1995-07-29        0    1.000000
10      1995-07-30        0    1.072000
11      1995-07-31        0    0.000000
12      1995-08-01        0    0.000000
13      1995-08-02        0    1.073000
14      1995-08-03        0    1.073000
15      1995-08-04        0    1.073000
16      1995-08-05        0    2.000000
17      1995-08-06        0    3.000000
18      1995-08-07        0    3.000000
19      1995-08-08        0    3.000000
20      1995-08-09        0   10.000000
21      1995-08-10        0   18.000000
22      1995-08-11        0   12.000000
23      1995-08-12        0   30.000000
24      1995-08-13        0   35.000000
25      1995-08-14        0   17.000000
26      1995-08-15        0    1.074000
27      1995-08-16        0    1.074000
28      1995-08-17        0    1.000000
29      1995-08-18        0    1.075000
...            ...      ...         ...
201786  2018-04-06       23  101.061224
201787  2018-04-07       23  115.247319
201788  2018-04-08       23  104.855346
201789  2018-04-09       23   96.150254
201790  2018-04-10       23   96.544901
201791  2018-04-11       23   95.951640
201792  2018-04-12       23  104.050235
201793  2018-04-13       23  115.019470
201794  2018-04-14       23  112.536146
201795  2018-04-15       23  102.413184
201796  2018-04-16       23   84.128662
201797  2018-04-17       23   82.310629
201798  2018-04-18       23  115.397910
201799  2018-04-19       23  130.148787
201800  2018-04-20       23   73.651514
201801  2018-04-21       23   73.040902
201802  2018-04-22       23   73.182921
201803  2018-04-23       23  117.952904
201804  2018-04-24       23  124.376789
201805  2018-04-25       23  140.515851
201806  2018-04-26       23   72.752131
201807  2018-04-27       23   71.669496
201808  2018-04-28       23   70.008969
201809  2018-04-29       23   70.012686
201810  2018-04-30       23   67.645951
201811  2018-05-01       23   64.229226
201812  2018-05-02       23   67.832816
201813  2018-05-03       23   63.710848
201814  2018-05-04       23   64.043453
201815  2018-05-05       23   75.242918

[201816 rows x 3 columns]